spring.application.name=jwtDemo

server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/jwtdb
spring.datasource.username=root
spring.datasource.password=Kanna@8985

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=JNHyAjF8DOUa4FtSkHjvIHd9zNqxbBizaMPtBjzym7S
app.jwt.expiration-ms=3600000